### ISSUE TITLE
[Editor Scripts-Mono] Editing script outside make Banshee exits (no errors), and crash on exit

### ISSUE THREAD

**Issue by christianclavet** [BearishSun/BansheeEngine#155]
Hi, Been trying to script using MSVC 2015 with Banshee to create a FPS type camera that can affect physic.

Done a quick level using primitive and seeing some visual glitchs. Objects like wall meshes are being clipped from the view while still in the frustum view. I've also seen some weird shadows coming from the directional light while moving in front of the light with the camera.

I created a small test project, and was able to post it here so you can check.

You only have to start "the game" and move the ball. The ball is moving but not rotating. Collision seem to work, but the ball mesh (primitive) should rotate while moving since I'm using a sphere collider...

I'm reporting a more important issue, where after doing numerous START/STOP and editing scripts, Banshee may completely close without any warning or crash error message.

Also, since I click the button to save the scene often, sometimes after updating the scripts (I've seen this also happen sometimes when updating assets in a scene), Banshee will ask me to give a name (when normally it should save directly without asking)

When this happen, if you close Banshee, it will crash 100%.
Here is the small project to check. Camera mecanic is still really WIP, but working.
[Scripting.zip](https://github.com/BearishSun/BansheeEngine/files/1637603/Scripting.zip)
![physic](https://user-images.githubusercontent.com/13395943/35023992-36171666-fb0b-11e7-8ad5-d60772f49b43.JPG)

**Comment by BearishSun** [comment]
The incorrect culling of objects should be fixed with, 8af92d17bab6d6c452316a8f793a6bc232b9ab79. Looking into the rest of the issues - the script related crash in particular is familiar to me, and might take a bit to resolve.

**Comment by christianclavet** [comment]
Thanks. Checked and it's good for the wall parts.
Checked the crash when I close the application now (from this project):
BansheeCore.dll crashed because of a reading violation at address 0x00007FFCCE6BE718.
Stack calls:
```
BansheeCore.dll - Bs::SceneObject::DestroyInternal() - line 97, 83
BansheeCore.dll - Bs::SceneObject::Destroy() - line76
BansheeCore.dll - Bs::Prefab()~Prefab() - Line 22
```
Could this be related to the primitive I used?

**Comment by BearishSun** [comment]
It was also related to the scripting system, but should be resolved with 2231fc8f967e30bc4ebd252e09434027f314fc2b.

Regarding the rigidbody not rotating. It was due to the default physics material having 0 friction. I have tweaked the default material so the behavior is more realistic and has some friction & bounciness (restitution). You can also assign your own physics material to a Collider, controlling these options manually per-object.

**Comment by christianclavet** [comment]
Hi, I have the sphere rotating correctly now! Thanks! I still have issue, when I update the script, Banshee crash. But I've not seen it close unexpectedly since this new build (21 jan 2018)

**Comment by christianclavet** [comment]
Hi, I updated my camera scripts so it's working better now. But I had to change the default gravity value to -32.
What was the default gravity value?

You can check the updated project here:
[Scripting.zip](https://github.com/BearishSun/BansheeEngine/files/1650105/Scripting.zip)
The player avatar is made of 2 objects and there is a script on each of them.
- the "foot", that contain the capsule collider and make the avatar move
- the "head", that contain the camera and does the rotation

Each of them use the inputs to make their stuff.

You use the ESC key to enable/disable the camera.
WASD for movement
C for CROUCH
LEFT SHIFT for SPRINT
SPACE for jump

If you check with the default gravity value when you jump, it was taking too much time to come down. Changed the value to -32 on Y on cameraHead.cs and seem to be much better.

**Comment by BearishSun** [comment]
The default gravity is -9.8. If that doesn't feel right I suggest trying to tweak linear drag (air resistance), height of the camera and size of the surrounding geometry (which alters the perspective of distance and speed).

Haven't had a time to check out the project, but note that there is a CharacterController component, intended specifically for character movement, and is usually a better choice than using a Rigidbody.

**Comment by BearishSun** [comment]
Hi. I'm trying to reproduce the issue with Banshee crashing after editing the script and doing multiple play/stop operations. I'm currently unable to reproduce the issue. 

Can you tell me how often does the issue happen? (e.g. after 5 script edits, or 100?). Does the crash happen right after a script edit, or does it happen when entering/existing play mode? Are you making any specific changes to the script, or does it appear random?

**Comment by christianclavet** [comment]
Humm.. It's difficult to tell. When I'm testing a script:
1-Save the script, Banshee update
2-Switch to run mode to see
3-Stop.

What I can say, is that since a while, I don't see it happen that often (Something changed, or I use a better syntax since I learned a little reading your script example). But it still happen.
When the editor close, I don't remember seeing it happen when I was testing (play mode). And it never happened at the moment the script was updated or exiting play mode. There is always some time before that happen.

Could happen when the stop mode resume and cleanup, or after script compilation and cleanup. I can't tell..

**Comment by BearishSun** [comment]
Thanks, I managed to reproduce eventually. Still trying to find a good set of steps that can reproduce the issue consistently.

**Comment by BearishSun** [comment]
I tracked down multiple issues with the scripting system that would cause crashes. It's hard to tell which issue you exactly experienced without a log, but I believe it should be resolved now. If you still see the problem please reopen the issue.

**Comment by christianclavet** [comment]
Thanks Marko! I will try to use the character controller in a script this weekend and see if I can parent to bone from code instead of using the GUI. Been looking at the C# API documentation a lot since last week! :)
