### ISSUE TITLE
Issue with shaders using forward lighting

### ISSUE THREAD

**Issue by Straditarion** [BearishSun/BansheeEngine#302]
I've tried many other aproaches at forward lighting integration, but this is a simple one that didn't cause compilation errors:
`#include "$ENGINE$\BasePass.bslinc"
#include "$ENGINE$\ForwardLighting.bslinc"
shader Surface
{
    mixin BasePass;
    mixin ForwardLighting;
    code
    {
		[alias(gAlbedoTex)]
        SamplerState gAlbedoSamp;

        Texture2D gAlbedoTex;

        float4 fsmain(in VStoFS input) : SV_Target0
        {
            SurfaceData surfaceData;
            surfaceData.albedo = gAlbedoTex.Sample(gAlbedoSamp, input.uv0);
            surfaceData.worldNormal = float4(0, 1, 0, 1);
            surfaceData.roughness = 0.5;
            surfaceData.metalness = 0;
            float3 lighting = calcLighting(input.worldPosition.xyz, input.position, input.uv0, surfaceData);
            return float4(lighting, 1.0f);
        }   
    };
};`

Yet caused a crash when assigned to a material:
[20190613_0008.zip](https://github.com/BearishSun/BansheeEngine/files/3283377/20190613_0008.zip)

There were also cases when I could assign the shader to a material, but it would crash in a similar way when the material was assigned to a renderer (properties wouldn't appear).

Forward shaders not using forward lighting work as expected, properties appear and nothing crashes.

**Comment by BearishSun** [comment]
Thanks. The crash looks like an issue I might have fixed yesterday. I'll take a closer look at this, but if you get to it before me, try with the latest version and see if that perhaps solves it.

**Comment by BearishSun** [comment]
(Just noticed this is BansheeEngine repo. The crash was fixed on `bsf` but wasn't propagated here yet. If you can test there do it, if not leave it to me.)

**Comment by Straditarion** [comment]
Just finished a build and the issue persists, crash log is pretty much the same.
Also, for me it displays that a latest commit was made 5 days ago for both, the engine and bsf, just in case.

**Comment by Straditarion** [comment]
The issue is no more!
