### ISSUE TITLE
no compile on late

### ISSUE THREAD

**Issue by erherhh4herh** [BearishSun/BansheeEngine#84]
Am in late version and don't launch. Myself in need of compile late feature without crashed am pooper don't worked. Helped me have late feature prevent crash. I grab source to have late feature compile. Thank.  IT COMPILE FINE JUST NOT LUNCH!!!!! Thank. 🥇

**Comment by BearishSun** [comment]
Please let me know which error message are you receiving, and upload the crash log, if one is generated.

**Comment by erherhh4herh** [comment]
https://mega.nz/#!qlFjhKAL!qNqzVizk7nTc3fxT5wbOG9Ew7UHW2FQYvDBnkUWJiIY

Here crash log. Not sure how happen. By the way, i latest version grab from git hub. Thank.

**Comment by BearishSun** [comment]
One of the shaders failed to compile but because the error happened during an earlier run the log isn't telling me what the exact error is.

If you delete Data/Engine/Timestamp.asset and Data/Editor/Timestamp.asset, it will force shaders to be re-imported next time you run Banshee. When you get a crash during that run, send me that specific log as it should contain additional information. Thanks.

**Comment by erherhh4herh** [comment]
got here: https://mega.nz/#!apE0RTKS!VrFGq485lbdpwBwMs51vs-JKnJ94tFutGbRXzbtFKPY

**Comment by BearishSun** [comment]
I'm not seeing the additional information required. Are you by any chance running under a Release configuration? If so, can you try repeating the process using Debug config?

**Comment by erherhh4herh** [comment]
I use the bug. It not open. Launching a new build Testimony to check bugger. TAKE LONG CAUSE COMPUTE AM POOPER :( AFTER FACT: This not working for me but work for you? Cause I grab late source not combine for me. Testimony for log bugger cause broke. I compile the course code. On side you think can build grand theft automatic game like engine the implement system? It's wondering :) :) :) Still compile but the the the is not lunching. F BUGER >:(

LINK LOG: https://mega.nz/#!K91kEYoK!tm_MtTPrZVxxBJUT6kkjVNkafTfRtxrNrZOyZeiCZxE
I CRAMMED INTO FILE AM SURE OF THE BUG VERSION NOW IT COMPILE AND STILL CRASH!!!
Thank for all helping.

**Comment by BearishSun** [comment]
Yep it works for me. Sadly the log doesn't contain the additional information (there should be more than one log entry), but I'm not sure what is going wrong. 

I've made some changes to the shader import system yesterday, that should perhaps help narrow down the issue, but they are not pushed yet. When I push them I'll let you know and you can try running the latest again and see if there are any changes.

**Comment by BearishSun** [comment]
I've pushed some changes. If you get latest, delete the Timestamp.asset files again and try running it, the error log might reveal more information.

**Comment by erherhh4herh** [comment]
Hear. I grab late source compile still crash thank: https://mega.nz/#!LksRBZgZ!rkGOsu0eBhQgEawNCDDXuTTVGqoHEcCY-OKng3gkK2Q

**Comment by BearishSun** [comment]
Alright, this is a different error. Shaders seem to have compiled fine now.

Now it seems to be failing to load managed (C#) code. Can you check if MBansheeEngine and MBansheeEditor projects compile correctly, if you try to compile them manually in VS? Are there any warnings or error messages?

**Comment by erherhh4herh** [comment]
Yes. Compile without warn. One thing notice: no folder on builded file. Have been moving from the compiled version cause no file similar in source :)

**Comment by BearishSun** [comment]
MBansheeEngine.dll and MBansheeEditor.dll should end up in the bin\Assemblies\Debug folder. You're saying this is empty?

Please don't move any files from the compiled version, it is a much older version and it will most certainly cause issues.

**Comment by erherhh4herh** [comment]
Info:
Compile vs 2017 x64 debug
Windows 10 x64
Compile whole solution
Open BansheeEditorExec.exe

TESTING NEW BUILDED BEAR ENGINE! BUILD NOW WAIT FOR FINISHED. ONE QUASTIONS YOU WORK THis alone? if it really impressed. :)

compile. no folder in compile. not sure what do wrong? still crash: https://mega.nz/#!DstBnBTa!DZE01PdHzG4ejs0fe8HI3SMGESn2VMRcL4Jt7g3YqNs

say not find "BansheeOpenAudio.dll" but in compile folder. moved every stuff "data. bin. mono." (from source not late compile version) folder to compile folder. really sad not work. thank for all helps.

**Comment by BearishSun** [comment]
Visual Studio 2017 isn't officially supported, so that might be the issue. See this page for a potential workaround: https://github.com/BearishSun/BansheeEngine/issues/72.

I don't think stuff is compiling correctly if it cannot find the .dlls. Can you try compiling the solution and send me a copy of the text from VS output window?

I work on it alone, aside from an occasional contributor.

**Comment by erherhh4herh** [comment]
compile on vs 2015. get in engine place cube and light then crash. log: https://mega.nz/#!KpFhRKqQ!bGY1yFP4NgWCJWGOro9scf2d2eCO6wg00sk-XI6rn-4

lot's of crash :(

**Comment by BearishSun** [comment]
This appears to be ran in Release mode, so the log doesn't contain much information. Try running in Debug and send that log.

**Comment by christianclavet** [comment]
Hi,

I've re-read the issue. And it's launching fine here for me. But, there is most of the time a long wait before I can see the Banshee logo. (Waiting for **more than 10 seconds after starting the application** before I can see the logo). I'm compiling on VS2015. It could be caused by the initialisation of Mono. 

So perhaps find a way to put the displaying of the logo in the first steps of initialisation so the user doesn't think the application is not launching?

As for the crashes, they've been reduced a lot since November...
